# Generated by Django 3.0.7 on 2020-07-01 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100, verbose_name='driver_name')),
                ('driver_phone', models.CharField(default='', max_length=15)),
            ],
            options={
                'verbose_name_plural': 'drivers',
                'db_table': 'drivers',
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_name', models.CharField(max_length=100, verbose_name='guide_name')),
                ('guide_phone', models.CharField(default='', max_length=15)),
            ],
            options={
                'verbose_name_plural': 'guides',
                'db_table': 'guides',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=16, verbose_name='vehicle_number')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_driver', to='itinerary.Driver')),
            ],
            options={
                'verbose_name_plural': 'vehicles',
                'db_table': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('itineraryname', models.CharField(default='', max_length=250)),
                ('itinerarydescription', models.TextField(blank=True, null=True)),
                ('numberadults', models.IntegerField()),
                ('numberchildren', models.IntegerField()),
                ('itinerarystatus', models.IntegerField(default=0)),
                ('monthyear', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_user', to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_inquiry', to='inquiries.Inquiry')),
            ],
            options={
                'verbose_name_plural': 'inquiries',
                'db_table': 'itineraries',
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daytype', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('itinerary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_Itinerary', to='itinerary.Itinerary')),
            ],
            options={
                'verbose_name_plural': 'days',
                'db_table': 'days',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_day', to='itinerary.Day')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'db_table': 'activities',
            },
        ),
    ]
