# Generated by Django 3.0.7 on 2020-07-02 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
        ('itinerary', '0003_auto_20200702_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='inquiries.Inquiry'),
        ),
    ]
