# Generated by Django 3.0.7 on 2020-07-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0004_auto_20200702_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
