# Generated by Django 3.0.7 on 2020-07-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro')], default='basic', max_length=20),
        ),
    ]
